### PR TITLE
Make UDTs usable

### LINKED ISSUE #116: Make UDTs usable again
Currently using `Define()` or `DefineAsync()`  when trying to define a UDT mapping. results in a `NotImplementedException`. This is due to the fact that the legacy driver used cluster metadata to fetch the UDT mapping definitions. Since our cluster is now bridged with Rust, fetching UDT metadata must also be bridged. 

UDTs are a core part of the driver so the priority of this is high. 

### How to fix:
- In `Session.cs` make `UserDefinedTypes` field be initiated as a instance of `UdtMappingDefinitions` instead of always being null.
- Bridge fetching UDT metadata with Rust (how to do this remains an open question right now).

### PR DESCRIPTION
**Pull request by Akvear**
## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~~[ ] I have provided docstrings for the public items that I want to introduce.~~
- ~~[ ] I have adjusted the documentation in `./docs/source/`.~~
- ~~[ ] I have adjusted the migration documentation (removed/changed API) in `./docs/source/migration-guide`.~~
- [x] I added appropriate `Fixes:` annotations to PR description.

## Reasoning
UDTs are a core part of the driver and the support for them is vital.

## What is happening
We create a `SerializerManager` which holds the mapping for UDTs. We also use the serializer that the manager holds instead of always using a `GenericSerializer`. 
We query Rust for the metadata of UDTs one by one, similar to how metadata is obtained for tables.
Tests that use UDTs have also been uncommented, `UdtMappingsTests` were moved to working integration tests.

fixes: #116

### CODE REVIEW

File: src/Cassandra/RustBridge/BridgedClusterState.cs [hunk 1]
```diff
@@ -361,6 +362,140 @@ internal List<string> GetTableNames(string keyspaceName)
...
+            {
+                var udtFieldsHandle = GCHandle.FromIntPtr(udtFieldsHandlePtr);
+                var udtFieldsList = (List<ColumnDesc>)udtFieldsHandle.Target;
+
+                var cqlTypeCode = (ColumnTypeCode)typeCode;
+                var field = new ColumnDesc
+                {
+                    Name = fieldName.ToManagedString(),
+                    TypeCode = cqlTypeCode,
+                    TypeInfo = typeInfoPtr != IntPtr.Zero ? BridgedRowSet.BuildTypeInfoFromHandle(typeInfoPtr, cqlTypeCode) : null
```
[the remark this answers is not in the document]
Comment (Akvear) [reply src/Cassandra/RustBridge/BridgedClusterState.cs]: Can a UDT field type be a UDT? - probably yes

[the remark this answers is not in the document]
Comment (Akvear) [reply src/Cassandra/RustBridge/BridgedClusterState.cs]: Regardless, there should be a better way to do this

File: src/Cassandra/Metadata.cs [hunk 2]
```diff
@@ -332,15 +332,23 @@ public MaterializedViewMetadata GetMaterializedView(string keyspace, string name
...
-            throw new NotImplementedException();
+            var session = _getActiveSessionOrThrow();
+            try
+            {
+                return session.GetClusterState().GetUdtMetadataAsync(keyspace, typeName);
+            }
+            finally
+            {
+                session.DecreaseReferenceCount();
+            }
```
[the remark this answers is not in the document]
Comment (Akvear) [reply src/Cassandra/Metadata.cs:348]: the public API exposes a `Task<UdtColumnInfo>` - this would require changing the API (and making it fake return Task). 

```csharp
public async Task<UdtColumnInfo> GetUdtDefinitionAsync(string keyspace, string typeName)
        {
            var session = _getActiveSessionOrThrow();
            try
            {
                var clusterState = session.GetClusterState();
                var result = await clusterState.GetUdtMetadataAsync(keyspace, typeName);
                return Task.FromResult(result);
            }
            finally
            {
                ClusterState.Dispose();
                session.DecreaseReferenceCount();
            }
        }
```
Something like this

**Review by sylwiaszunejko — COMMENTED** [review]
From C# side looks good, but I will wait with approve until @wprzytula review Rust code

File: rust/src/metadata.rs [hunk 3]
```diff
@@ -413,6 +413,105 @@ pub extern "C" fn cluster_state_get_table_names(
...
+    type_info: BridgedBorrowedSharedPtr<'_, ColumnType<'_>>,
+) -> FFIMaybeException;
+
+/// Opaque type representing the C# UDT context.
+enum UdtContext {}
+
+/// Transparent wrapper around a pointer to the C# UDT context.
+#[derive(Clone, Copy)]
+#[repr(transparent)]
+pub struct UdtContextPtr(FFIPtr<'static, UdtContext>);
```
Comment (wprzytula) [inline rust/src/metadata.rs]: 💭 If `UdtContext` is not allocated using `GCHandle`, but instead passed by our _pointer to stack trick_, its lifetime is not `'static`. For memory safety (to avoid UAF), you should make `UdtContextPtr` parametrised by a lifetime.

File: rust/src/metadata.rs [hunk 4]
```diff
@@ -413,6 +413,105 @@ pub extern "C" fn cluster_state_get_table_names(
...
+
+/// SAFETY: This type is Send because it only contains a raw pointer that is never dereferenced on the Rust side.
+unsafe impl Send for UdtContextPtr {}
```
Comment (wprzytula) [inline rust/src/metadata.rs]: 💭 Even if it's never dereferenced on the Rust side, but it is dereferenced by C# callback called by the tokio worker thread, this still means switching threads. Thus the true Send property is needed.

File: rust/src/metadata.rs [hunk 5]
```diff
@@ -413,6 +413,105 @@ pub extern "C" fn cluster_state_get_table_names(
...
+pub extern "C" fn cluster_state_get_udt_metadata_async(
+    tcb: Tcb<FFIBool>,
+    cluster_state_ptr: BridgedBorrowedSharedPtr<'_, ClusterState>,
+    keyspace_name: CSharpStr<'_>,
+    udt_name: CSharpStr<'_>,
+    construct_udt_field: ConstructCSharpUdtField,
+    udt_context_ptr: UdtContextPtr,
+    construct_udt_metadata: ConstructCSharpUdtMetadata,
+    constructors: &'static ExceptionConstructors,
+) {
```
Comment (wprzytula) [inline rust/src/metadata.rs]: ❓ Why is this `async`? Does this perform any I/O at all?

File: rust/src/metadata.rs [hunk 6]
```diff
@@ -413,6 +413,105 @@ pub extern "C" fn cluster_state_get_table_names(
...
+                return Err(exception_ptr);
+            }
+        }
+
+        let ffi_exception =
+            unsafe { construct_udt_metadata(udt_context_ptr, FFIStr::new(udt.name.as_ref())) };
+
+        if let Some(exception_ptr) = ffi_exception.try_into_ffi_exception() {
+            return Err(exception_ptr);
+        }
```
Comment (wprzytula) [inline rust/src/metadata.rs]:
```suggestion
        let maybe_ffi_exception =
            unsafe { construct_udt_metadata(udt_context_ptr, FFIStr::new(udt.name.as_ref())) };

        if let Some(ffi_exception) = maybe_ffi_exception.try_into_ffi_exception() {
            return Err(ffi_exception)
```

File: src/Cassandra/RustBridge/BridgedClusterState.cs [hunk 7]
```diff
@@ -361,6 +362,135 @@ internal List<string> GetTableNames(string keyspaceName)
...
+                    TypeInfo = typeInfoPtr != IntPtr.Zero ? BridgedRowSet.BuildTypeInfoFromHandle(typeInfoPtr, cqlTypeCode, context.KeyspaceName) : null
+                };
+                context.Fields.Add(field);
+                return FFIMaybeException.Ok();
+            }
+            catch (Exception ex)
+            {
+                return FFIMaybeException.FromException(ex);
+            }
+        }
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedClusterState.cs:420]: ❓ How is this function _Async_? I don't see any Task involved or anything like this.

File: src/Cassandra/RustBridge/BridgedClusterState.cs [hunk 8]
```diff
@@ -361,6 +362,135 @@ internal List<string> GetTableNames(string keyspaceName)
...
+
+        private static readonly unsafe delegate* unmanaged[Cdecl]<IntPtr, FFIString, FFIMaybeException> FillUdtMetadataAsyncPtr = &FillUdtMetadataAsync;
+
+        [UnmanagedCallersOnly(CallConvs = new Type[] { typeof(CallConvCdecl) })]
+        private static unsafe FFIMaybeException FillUdtMetadataAsync(
+            IntPtr udtContextHandlePtr,
+            FFIString udtName)
+        {
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedClusterState.cs:428]: ditto about `Async`.

File: src/Cassandra/RustBridge/BridgedClusterState.cs [hunk 9]
```diff
@@ -361,6 +362,135 @@ internal List<string> GetTableNames(string keyspaceName)
...
+            try
+            {
+                var contextHandle = GCHandle.FromIntPtr(udtContextHandlePtr);
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedClusterState.cs]: 🔧 Use the newly merged `FFIGCHandle`.

File: src/Cassandra/RustBridge/BridgedClusterState.cs [hunk 10]
```diff
@@ -361,6 +362,135 @@ internal List<string> GetTableNames(string keyspaceName)
...
+                var context = (UdtContext)contextHandle.Target;
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedClusterState.cs]: Why casting instead of the already widely used pattern of cast attempts using `if X is Y`?

File: src/Cassandra/RustBridge/BridgedClusterState.cs [hunk 11]
```diff
@@ -361,6 +362,135 @@ internal List<string> GetTableNames(string keyspaceName)
...
+            catch (Exception ex)
+            {
+                return FFIMaybeException.FromException(ex);
+            }
+        }
+
+        internal async Task<UdtColumnInfo> GetUdtMetadataAsync(string keyspaceName, string udtName)
+        {
+            var context = new UdtContext(keyspaceName);
+            var contextHandle = GCHandle.Alloc(context);
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedClusterState.cs]: 🔧 Use the `FFIGCHandle`.

File: src/Cassandra/RustBridge/BridgedRowSet.cs [hunk 12]
```diff
@@ -254,6 +254,10 @@ internal static IColumnInfo BuildTypeInfoFromHandle(IntPtr handle, ColumnTypeCod
                         {
                             row_set_type_info_get_udt_name(handle, out FFIString udtName);
                             var name = udtName.ToManagedString();
+                            if (!string.IsNullOrEmpty(name) && name.IndexOf('.') < 0 && !string.IsNullOrEmpty(keyspaceHint))
+                            {
+                                name = $"{keyspaceHint}.{name}";
+                            }
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedRowSet.cs]: 🤔 This looks fragile. Explain in a comment:
1. why keyspace addition is needed;
2. why it's possible that `null` keyspace is provided;
3. why it's possible that the keyspace name contains the period, and why the opposite is also possible.

Comment (wprzytula) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: ❓ What are the consequences of not adding the `keyspace.` part to the UDT name?

File: src/Cassandra.IntegrationTests/Core/TypeSerializerTests.cs [hunk 13]
```diff
@@ -104,12 +102,12 @@ private static IEnumerable VectorTestCaseData()
...
+                    new TestCaseData("fixed_type", (Func<FixedType>)(()=>new FixedType { a = r.Next(), b = r.Next()}), defaultAssert),
+                    new TestCaseData("mixed_type_one", (Func<MixedTypeOne>)(()=>new MixedTypeOne { a = r.Next(), b = (long)r.NextDouble()}), defaultAssert),
+                    new TestCaseData("mixed_type_two", (Func<MixedTypeTwo>)(()=>new MixedTypeTwo { a = (long)r.NextDouble(), b = r.Next()}), defaultAssert),
+                    new TestCaseData("var_type", (Func<VarType>)(()=>new VarType { a = (long)r.NextDouble(), b = (long)r.NextDouble()}), defaultAssert),
+                    new TestCaseData("complex_vector_udt", (Func<ComplexVectorUdt>)(()=>new ComplexVectorUdt { a = new CqlVector<int>(r.Next(), r.Next(), r.Next()), b = new CqlVector<BigInteger>(r.Next(), r.Next(), r.Next())}), defaultAssert),
+                    new TestCaseData("nested_type", (Func<NestedType>)(()=>new NestedType { a = r.Next(), b = new FixedType { a = r.Next(), b = r.Next() } }), defaultAssert),
```
Comment (wprzytula) [inline src/Cassandra.IntegrationTests/Core/TypeSerializerTests.cs:110]: ❓ Is the case for `nested_type` added here? I can't see it in the previous version.
If so, it probably should be added in a separate commit.

**Review by wprzytula — CHANGES_REQUESTED** [review]

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 12 above)
Comment (Akvear) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: Serializer doesnt recognize the type and throws an exception.

File: rust/src/metadata.rs (hunk 5 above)
Comment (Akvear) [reply rust/src/metadata.rs]: `public Task<UdtColumnInfo> GetUdtDefinitionAsync()`. Because this function returns a `Task<T>`. I am not sure whether this should be done or something like in https://github.com/scylladb-zpp-2025-csharp-rs-driver/csharp-driver/pull/122#discussion_r3073585580 but without the await.

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 12 above)
Comment (Akvear) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: 2. null is the default value of `keyspaceHint`. `BuildTypeInfoFromHandle` is called when fetching UDT metadata and while fetching table metadata(which doesnt require the keyspace prefix)
3. It's the udtName - not the keyspace name. I guess this check is not really necessary. 

In general the naming should probably be unified between the Rust and C# drivers, but I don't know how important the keyspace prefix is down the road.

Comment (wprzytula) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: > 2. null is the default value of `keyspaceHint`. `BuildTypeInfoFromHandle` is called when fetching UDT metadata and while fetching table metadata(which doesnt require the keyspace prefix)

IIUC, the issue here arises from reusing `BuildTypeInfoFromHandle` in two cases, one of which requires `keyspaceHint` and one not. Perhaps the solution is to have two separate functions: one taking the mandatory `keyspaceHint` and the other not taking it at all?
> 
>   3. It's the udtName - not the keyspace name. I guess this check is not really necessary.

I agree.
 
> In general the naming should probably be unified between the Rust and C# drivers, but I don't know how important the keyspace prefix is down the road.

WDYM?

File: rust/src/metadata.rs (hunk 5 above)
Comment (wprzytula) [reply rust/src/metadata.rs]: Functions should only use the async machinery if they need it for anything. Even if a function must return a Task, it is perfectly OK to create it synchronously.

What I'd do here is implementing the `DoSomethingAsync` functions simply as:
```c#
var res = DoSomething();
return Task.FromResult(res);

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 12 above)
Comment (wprzytula) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: You haven't responded to my question. Unresolving.

File: rust/src/metadata.rs (hunk 3 above)
Comment (wprzytula) [reply rust/src/metadata.rs]: I still see `'static` there.

File: src/Cassandra/KeyspaceMetadata.cs [hunk 14]
```diff
@@ -228,15 +228,15 @@ public string AsCqlQuery()
...
         }
 
         /// <summary>
         /// Gets the definition of a User defined type asynchronously
         /// </summary>
         internal Task<UdtColumnInfo> GetUdtDefinitionAsync(string typeName)
         {
-            throw new NotImplementedException("TODO: implement UdtMetadata");
+            return Task.FromResult(GetUdtDefinition(typeName));
         }
```
Comment (wprzytula) [inline src/Cassandra/KeyspaceMetadata.cs]: 🔧 This can (and should IMO) be deleted, as it's not a public API.

File: src/Cassandra/RustBridge/BridgedRowSet.cs [hunk 15]
```diff
@@ -203,11 +203,15 @@ private nuint GetColumnsCount()
...
-        internal static IColumnInfo BuildTypeInfoFromHandle(IntPtr handle, ColumnTypeCode code, string keyspaceHint = null)
+        internal static IColumnInfo BuildTypeInfoFromHandle(IntPtr handle, ColumnTypeCode code, string keyspaceHint)
         {
             if (handle == IntPtr.Zero) return null;
             try
             {
+                if (keyspaceHint == null)
+                {
+                    throw new ArgumentNullException(nameof(keyspaceHint), "Keyspace hint cannot be null when building column type info from handle.");
+                }
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedRowSet.cs]: > // This function is called from UnmanagedCallersOnly context - it must not throw exceptions.

> throw new ArgumentNullException(nameof(keyspaceHint), "Keyspace hint cannot be null when building column type info from handle.");

File: src/Cassandra/RowPopulators/RowSet.cs [hunk 16]
```diff
@@ -121,6 +122,16 @@ internal RowSet(RustBridge.ManuallyDestructible mdRowSet)
...
+        }
+
+        internal RowSet(RustBridge.ManuallyDestructible mdRowSet, ISerializerManager serializerManager)
+        {
+            bridgedRowSet = new BridgedRowSet(mdRowSet);
+            Columns = bridgedRowSet.ExtractColumnsFromRust();
+            _exhausted = Columns.Length == 0;
+            Info = new ExecutionInfo();
+            _genericSerializer = serializerManager?.GetGenericSerializer() ?? new GenericSerializer();
         }
```
Comment (wprzytula) [inline src/Cassandra/RowPopulators/RowSet.cs:126]: ❓ Can we delete the old constructor? The new one is strictly better, because it caches the serializer.

**Review by wprzytula — CHANGES_REQUESTED** [review]
Is the commit [Use a specified session serializer manager instead of default serializer](https://github.com/scylladb-zpp-2025-csharp-rs-driver/csharp-driver/pull/122/changes/1f7006a9ce385d83153a401a50139432d9dcffd0) needed for the UDTs to work correctly?

If not, I'd prefer to exclude it from this PR, and send it as a separate PR.
This is because @phalat24 has the optimisation in #105 which possibly obsoletes your changes.

**Comment by Akvear** [comment]
> Is the commit [Use a specified session serializer manager instead of default serializer](https://github.com/scylladb-zpp-2025-csharp-rs-driver/csharp-driver/pull/122/changes/1f7006a9ce385d83153a401a50139432d9dcffd0) needed for the UDTs to work correctly?
> 
> If not, I'd prefer to exclude it from this PR, and send it as a separate PR. This is because @phalat24 has the optimisation in #105 which possibly obsoletes your changes.

Yes, otherwise we always use the `GenericSerializer` which doesn't know how to serialize and desiarialize UDTs.

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 12 above)
Comment (Akvear) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: Actually all paths require the keyspace name, so I changed `BuildTypeInfoFromHandle` to always require one. This was overlooked back in November.

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 15 above)
Comment (Akvear) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: The comment is misleading - as the exceptions that are thrown are caught and the program is aborted with a `FailFast`.

File: src/Cassandra/RowPopulators/RowSet.cs (hunk 16 above)
Comment (Akvear) [reply src/Cassandra/RowPopulators/RowSet.cs:126]: I see no reason not to

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 15 above)
Comment (wprzytula) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: Then please update the comment.

**Comment by wprzytula** [comment]
> > Is the commit [Use a specified session serializer manager instead of default serializer](https://github.com/scylladb-zpp-2025-csharp-rs-driver/csharp-driver/pull/122/changes/1f7006a9ce385d83153a401a50139432d9dcffd0) needed for the UDTs to work correctly?
> > If not, I'd prefer to exclude it from this PR, and send it as a separate PR. This is because @phalat24 has the optimisation in #105 which possibly obsoletes your changes.
> 
> Yes, otherwise we always use the `GenericSerializer` which doesn't know how to serialize and desiarialize UDTs.

OK. Will your changes require complex handling in @phalat24's code?

**Comment by Akvear** [comment]
WDYM by complex handling?

**Comment by wprzytula** [comment]
> WDYM by complex handling?

How much do your changes conflict / get obsoleted by #105?

**Comment by Akvear** [comment]
It will require some changes to #105 - but this changes are required for UDTs to work. From what i can tell this PR ties a `SerializerManager` to a `Session`, while #105 ties it to `SerializationHandler`. Apart from that I don't think it overlaps that much.

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 12 above)
Comment (Akvear) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: > > In general the naming should probably be unified between the Rust and C# drivers, but I don't know how important the keyspace prefix is down the road.
> 
> WDYM?

What I meant is that maybe we should change the way C# driver stores UDT names to be the same as Rust (so without the prefix), but I don't know how important it is in the inner infrastructure of the C# driver.

File: rust/src/metadata.rs [hunk 17]
```diff
@@ -413,6 +413,95 @@ pub extern "C" fn cluster_state_get_table_names(
     }
 }
 
+/// Opaque type representing the C# UdtContext.
+pub enum UdtContext {}
```
Comment (wprzytula) [inline rust/src/metadata.rs]: ⛏️ This can be `pub(self)` (= you can remove the `pub`).

File: src/Cassandra/RustBridge/BridgedRowSet.cs [hunk 18]
```diff
@@ -202,12 +202,16 @@ private nuint GetColumnsCount()
             return count;
         }
 
-        // This function is called from UnmanagedCallersOnly context - it must not throw exceptions.
-        internal static IColumnInfo BuildTypeInfoFromHandle(IntPtr handle, ColumnTypeCode code, string keyspaceHint = null)
+        // This function is called from UnmanagedCallersOnly context - all thrown exceptions must be caught.
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedRowSet.cs]: ⛏️ This is still misleading: this makes me believe the exceptions must be caught in this function, which is not needed.

**Review by wprzytula — CHANGES_REQUESTED** [review]

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 18 above)
Comment (Akvear) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: What would be a good alternative?

Comment (wprzytula) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: It depends on what you want this comment to convey.

File: src/Cassandra/RustBridge/BridgedRowSet.cs (hunk 12 above)
Comment (wprzytula) [reply src/Cassandra/RustBridge/BridgedRowSet.cs]: Can you open an issue to investigate that, including the motivation?

File: src/Cassandra/RustBridge/BridgedRowSet.cs [hunk 19]
```diff
@@ -202,12 +202,16 @@ private nuint GetColumnsCount()
             return count;
         }
 
-        // This function is called from UnmanagedCallersOnly context - it must not throw exceptions.
-        internal static IColumnInfo BuildTypeInfoFromHandle(IntPtr handle, ColumnTypeCode code, string keyspaceHint = null)
+        // This function is called from UnmanagedCallersOnly context - make sure no exceptions crosses the FFI boundary.
```
Comment (wprzytula) [inline src/Cassandra/RustBridge/BridgedRowSet.cs]:
```suggestion
        // This function is called from UnmanagedCallersOnly context - make sure no exceptions cross the FFI boundary.
```

**Review by wprzytula — APPROVED** [review]

**Comment by Akvear** [comment]
should be good to merge now
